fix: Restart flatpaks setup on install failure

diff --git a/files/usr/bin/system-flatpak-setup b/files/usr/bin/system-flatpak-setup
--- a/files/usr/bin/system-flatpak-setup
+++ b/files/usr/bin/system-flatpak-setup
@@ -50,7 +50,10 @@ REMOVE_LIST=$(cat /etc/flatpak/system/remove)
 
 # Install flatpaks in list
 if [[ -n $INSTALL_LIST ]]; then
-    flatpak install --system --noninteractive $REPO_NAME ${INSTALL_LIST[@]}
+    if ! flatpak install --system --noninteractive $REPO_NAME ${INSTALL_LIST[@]}; then
+        # Exit on error
+        exit 1
+    fi
 fi
 
 # Remove flatpaks in list
diff --git a/files/usr/bin/user-flatpak-setup b/files/usr/bin/user-flatpak-setup
--- a/files/usr/bin/user-flatpak-setup
+++ b/files/usr/bin/user-flatpak-setup
@@ -41,7 +41,10 @@ REMOVE_LIST=$(cat /etc/flatpak/user/remove)
 
 # Install flatpaks in list
 if [[ -n $INSTALL_LIST ]]; then
-    flatpak install --user --noninteractive $REPO_NAME ${INSTALL_LIST[@]}
+    if ! flatpak install --user --noninteractive $REPO_NAME ${INSTALL_LIST[@]}; then
+        # Exit on error
+        exit 1
+    fi
 fi
 
 # Remove flatpaks in list
